const productsData = [
    {
        category: 1,
        condition: 8,
        created_at: "2023-10-19",
        description: "Classic novel by a renowned author.",
        for_borrow: true,
        for_sale: true,
        id: "product3",
        image: "product3.jpg",
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "pride and prejudice",
        price: 9.99,
        uid: "user789",
    },
    {
        category: 4,
        condition: 10,
        created_at: "2023-10-19",
        description: "Comfortable sofa, barely used.",
        for_borrow: false,
        for_sale: true,
        id: "product4",
        image: "product4.jpg",
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "comfy sofa",
        price: 299.99,
        uid: "user101",
    },
    {
        category: 1,
        condition: 5,
        created_at: "2023-10-19",
        description: "High-performance laptop for gaming and work.",
        for_borrow: false,
        for_sale: true,
        id: "product5",
        image: "product5.jpg",
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "gaming laptop x",
        price: 1299.99,
        uid: "user567",
    },
    {
        category: 3,
        condition: 2,
        created_at: "2023-10-19",
        description: "Elegant dress for special occasions.",
        for_borrow: true,
        for_sale: true,
        id: "product6",
        image: "product6.jpg",
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "evening gown",
        price: 79.99,
        uid: "user345",
    },
    {
        category: 5,
        condition: 9,
        created_at: "2023-10-19",
        description: "Durable hiking backpack with multiple compartments.",
        for_borrow: true,
        for_sale: true,
        id: "product7",
        image: "product7.jpg",
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "hiking backpack",
        price: 39.99,
        uid: "user234",
    },
    {
        category: 1,
        condition: 9,
        created_at: "2023-10-19",
        description: "Smart home security camera with night vision.",
        for_borrow: false,
        for_sale: true,
        id: "product8",
        image: "product8.jpg",
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "security camera pro",
        price: 149.99,
        uid: "user678",
    },
    {
        category: 3,
        condition: 3,
        created_at: "2023-10-19",
        description: "Interactive robot toy for kids.",
        for_borrow: true,
        for_sale: true,
        id: "product9",
        image: "product9.jpg",
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "robo buddy",
        price: 49.99,
        uid: "user890",
    },
    {
        category: 6,
        condition: 9,
        created_at: "2023-10-19",
        description: "Elegant diamond necklace in a gift box.",
        for_borrow: true,
        for_sale: true,
        id: "product10",
        image: "product10.jpg",
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "diamond necklace",
        price: 299.99,
        uid: "user123",
    },
    {
        category: 7,
        condition: 7,
        created_at: "2023-10-19",
        description: "Power drill with a set of drill bits.",
        for_borrow: false,
        for_sale: true,
        id: "product11",
        image: "product11.jpg",
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "power drill kit",
        price: 79.99,
        uid: "user456",
    },
    {
        category: 6,
        condition: 5,
        created_at: "2023-10-19",
        description: "High-speed blender for smoothies and more.",
        for_borrow: true,
        for_sale: true,
        id: "product12",
        image: "product12.jpg",
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "smoothie blender",
        price: 59.99,
        uid: "user789",
    },
    {
        category: 3,
        condition: 6,
        created_at: "2023-10-19",
        description: "Stylish men's dress shirt in multiple colors.",
        for_borrow: true,
        for_sale: true,
        id: "product13",
        image: "product13.jpg",
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "men's dress shirt",
        price: 29.99,
        uid: "user101",
    },
    {
        category: 5,
        condition: 2,
        created_at: "2023-10-19",
        description: "Set of golf clubs with a golf bag.",
        for_borrow: false,
        for_sale: true,
        id: "product14",
        image: "product14.jpg",
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "golf club set",
        price: 199.99,
        uid: "user567",
    },
    {
        category: 1,
        condition: 10,
        created_at: "2023-10-19",
        description: "Wireless noise-canceling headphones for music lovers.",
        for_borrow: false,
        for_sale: true,
        id: "product15",
        image: "product15.jpg",
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "noise-canceling headphones",
        price: 149.99,
        uid: "user345",
    },
    {
        category: 4,
        condition: 10,
        created_at: "2023-10-19",
        description: "Artistic wall painting with a wooden frame.",
        for_borrow: true,
        for_sale: true,
        id: "product16",
        image: "product16.jpg",
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "wall art painting",
        price: 69.99,
        uid: "user234",
    },
    {
        category: 7,
        condition: 7,
        created_at: "2023-10-19",
        description: "Educational building blocks for kids.",
        for_borrow: true,
        for_sale: true,
        id: "product17",
        image: "product17.jpg",
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "building blocks set",
        price: 19.99,
        uid: "user678",
    },
    {
        category: 6,
        condition: 9,
        created_at: "2023-10-19",
        description: "Silver bracelet with intricate design.",
        for_borrow: false,
        for_sale: true,
        id: "product18",
        image: "product18.jpg",
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "silver bracelet",
        price: 39.99,
        uid: "user890",
    },
    {
        category: 7,
        condition: 5,
        created_at: "2023-10-19",
        description: "Cordless electric screwdriver with accessories.",
        for_borrow: true,
        for_sale: true,
        id: "product19",
        image: "product19.jpg",
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "cordless screwdriver kit",
        price: 49.99,
        uid: "user123",
    },
    {
        category: 5,
        condition: 8,
        created_at: "2023-10-19",
        description: "Compact coffee maker for single servings.",
        for_borrow: false,
        for_sale: true,
        id: "product20",
        image: "product20.jpg",
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "single serve coffee maker",
        price: 29.99,
        uid: "user456",
    },
];

export default productsData;
