import { addDoc, collection } from "firebase/firestore";

import { db } from "@/lib/firebase";

const productsData = [
    {
        category: 1,
        condition: 8,
        created_at: "2023-09-05",
        description: "Classic literature set for book enthusiasts.",
        for_borrow: true,
        for_sale: false,
        index: 0,
        id: "product0",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Classic literature set",
        price: 99.95,
        uid: "user123",
    },
    {
        category: 3,
        condition: 7,
        created_at: "2023-08-12",
        description: "Handcrafted leather wallet for a touch of elegance.",
        for_borrow: false,
        for_sale: true,
        index: 1,
        id: "product1",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Handcrafted leather wallet",
        price: 49.99,
        uid: "user456",
    },
    {
        category: 5,
        condition: 9,
        created_at: "2023-10-25",
        description: "Gourmet coffee collection for coffee connoisseurs.",
        for_borrow: true,
        for_sale: true,
        index: 2,
        id: "product2",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Gourmet coffee collection",
        price: 29.95,
        uid: "user789",
    },
    {
        category: 2,
        condition: 6,
        created_at: "2023-11-01",
        description: "Vintage vinyl record player for music aficionados.",
        for_borrow: false,
        for_sale: true,
        index: 3,
        id: "product3",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Vintage vinyl record player",
        price: 199.99,
        uid: "user234",
    },
    {
        category: 4,
        condition: 7,
        created_at: "2023-10-18",
        description: "Artistic painting set for creative individuals.",
        for_borrow: true,
        for_sale: true,
        index: 4,
        id: "product4",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Artistic painting set",
        price: 79.99,
        uid: "user567",
    },
    {
        category: 1,
        condition: 9,
        created_at: "2023-09-20",
        description: "Cookbook collection for aspiring chefs.",
        for_borrow: true,
        for_sale: true,
        index: 5,
        id: "product5",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Cookbook collection",
        price: 69.99,
        uid: "user890",
    },
    {
        category: 3,
        condition: 8,
        created_at: "2023-08-30",
        description: "Stylish sunglasses for fashion-forward individuals.",
        for_borrow: false,
        for_sale: true,
        index: 6,
        id: "product6",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Stylish sunglasses",
        price: 39.99,
        uid: "user345",
    },
    {
        category: 5,
        condition: 10,
        created_at: "2023-09-15",
        description: "Tea variety pack for tea enthusiasts.",
        for_borrow: true,
        for_sale: true,
        index: 7,
        id: "product7",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Tea variety pack",
        price: 24.99,
        uid: "user678",
    },
    {
        category: 2,
        condition: 7,
        created_at: "2023-10-03",
        description: "Antique camera for photography enthusiasts.",
        for_borrow: false,
        for_sale: true,
        index: 8,
        id: "product8",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Antique camera",
        price: 149.99,
        uid: "user987",
    },
    {
        category: 4,
        condition: 9,
        created_at: "2023-09-10",
        description: "Sculpture set for art enthusiasts.",
        for_borrow: true,
        for_sale: true,
        index: 9,
        id: "product9",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Sculpture set",
        price: 129.99,
        uid: "user543",
    },

    {
        category: 2,
        condition: 8,
        created_at: "2023-10-01",
        description: "Smartwatch with health monitoring features.",
        for_borrow: false,
        for_sale: true,
        index: 10,
        id: "product10",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Health Monitoring Smartwatch",
        price: 199.99,
        uid: "user678",
    },
    {
        category: 4,
        condition: 7,
        created_at: "2023-09-25",
        description: "Calligraphy set for creative writing enthusiasts.",
        for_borrow: true,
        for_sale: true,
        index: 11,
        id: "product11",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Calligraphy Set",
        price: 59.99,
        uid: "user234",
    },
    {
        category: 1,
        condition: 9,
        created_at: "2023-08-20",
        description: "Home gardening kit for plant lovers.",
        for_borrow: true,
        for_sale: true,
        index: 12,
        id: "product12",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Home Gardening Kit",
        price: 79.99,
        uid: "user567",
    },
    {
        category: 3,
        condition: 8,
        created_at: "2023-10-10",
        description: "Luxury fountain pen for writing enthusiasts.",
        for_borrow: false,
        for_sale: true,
        index: 13,
        id: "product13",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Luxury Fountain Pen",
        price: 129.99,
        uid: "user890",
    },
    {
        category: 5,
        condition: 7,
        created_at: "2023-09-30",
        description: "Collection of rare spices for culinary artists.",
        for_borrow: true,
        for_sale: true,
        index: 14,
        id: "product14",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Rare Spices Collection",
        price: 49.99,
        uid: "user345",
    },
    {
        category: 4,
        condition: 10,
        created_at: "2023-08-27",
        description: "Knitting kit for crafting cozy accessories.",
        for_borrow: true,
        for_sale: true,
        index: 15,
        id: "product15",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Knitting Kit",
        price: 69.99,
        uid: "user123",
    },
    {
        category: 3,
        condition: 9,
        created_at: "2023-10-05",
        description: "Designer wristwatch for style and functionality.",
        for_borrow: false,
        for_sale: true,
        index: 16,
        id: "product16",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Designer Wristwatch",
        price: 299.99,
        uid: "user456",
    },
    {
        category: 2,
        condition: 8,
        created_at: "2023-09-15",
        description: "Portable Bluetooth speaker for music enthusiasts.",
        for_borrow: true,
        for_sale: true,
        index: 17,
        id: "product17",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Portable Bluetooth Speaker",
        price: 79.99,
        uid: "user789",
    },
    {
        category: 1,
        condition: 7,
        created_at: "2023-08-25",
        description: "DIY home brewing kit for beer enthusiasts.",
        for_borrow: true,
        for_sale: true,
        index: 18,
        id: "product18",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "DIY Home Brewing Kit",
        price: 89.99,
        uid: "user234",
    },
    {
        category: 5,
        condition: 9,
        created_at: "2023-09-12",
        description: "Rare tea set for tea aficionados.",
        for_borrow: true,
        for_sale: true,
        index: 19,
        id: "product19",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Rare Tea Set",
        price: 39.99,
        uid: "user567",
    },
    {
        category: 3,
        condition: 8,
        created_at: "2023-08-10",
        description: "Leather-bound journal for writing enthusiasts.",
        for_borrow: false,
        for_sale: true,
        index: 20,
        id: "product20",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Leather-Bound Journal",
        price: 19.99,
        uid: "user890",
    },
    {
        category: 4,
        condition: 7,
        created_at: "2023-09-18",
        description: "Wood carving set for craft enthusiasts.",
        for_borrow: true,
        for_sale: true,
        index: 21,
        id: "product21",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Wood Carving Set",
        price: 49.99,
        uid: "user345",
    },
    {
        category: 1,
        condition: 9,
        created_at: "2023-10-20",
        description: "Plant-based cookbook collection for chefs.",
        for_borrow: true,
        for_sale: true,
        index: 22,
        id: "product22",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Plant-Based Cookbook Collection",
        price: 59.99,
        uid: "user123",
    },
    {
        category: 5,
        condition: 8,
        created_at: "2023-09-02",
        description: "Premium herbal tea assortment for tea lovers.",
        for_borrow: true,
        for_sale: true,
        index: 23,
        id: "product23",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Premium Herbal Tea Assortment",
        price: 29.99,
        uid: "user456",
    },
    {
        category: 2,
        condition: 9,
        created_at: "2023-09-28",
        description: "Wireless earbuds for music enthusiasts.",
        for_borrow: false,
        for_sale: true,
        index: 24,
        id: "product24",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Wireless Earbuds",
        price: 129.99,
        uid: "user789",
    },
    {
        category: 3,
        condition: 7,
        created_at: "2023-08-15",
        description: "Vintage typewriter for writing enthusiasts.",
        for_borrow: true,
        for_sale: true,
        index: 25,
        id: "product25",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Vintage Typewriter",
        price: 249.99,
        uid: "user234",
    },
    {
        category: 1,
        condition: 8,
        created_at: "2023-10-22",
        description: "Baking essentials kit for home bakers.",
        for_borrow: true,
        for_sale: true,
        index: 26,
        id: "product26",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Baking Essentials Kit",
        price: 79.99,
        uid: "user567",
    },
    {
        category: 5,
        condition: 9,
        created_at: "2023-09-08",
        description: "Exotic tea leaves assortment for tea enthusiasts.",
        for_borrow: true,
        for_sale: true,
        index: 27,
        id: "product27",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Exotic Tea Leaves Assortment",
        price: 34.99,
        uid: "user345",
    },
    {
        category: 2,
        condition: 7,
        created_at: "2023-09-05",
        description: "Wireless gaming headset for gaming enthusiasts.",
        for_borrow: false,
        for_sale: true,
        index: 28,
        id: "product28",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Wireless Gaming Headset",
        price: 149.99,
        uid: "user890",
    },
    {
        category: 4,
        condition: 8,
        created_at: "2023-08-30",
        description: "Ceramic pottery set for art enthusiasts.",
        for_borrow: true,
        for_sale: true,
        index: 29,
        id: "product29",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Ceramic Pottery Set",
        price: 69.99,
        uid: "user123",
    },

    {
        category: 1,
        condition: 9,
        created_at: "2023-09-19",
        description: "Gourmet chocolate box for chocolate lovers.",
        for_borrow: true,
        for_sale: true,
        index: 30,
        id: "product30",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Gourmet Chocolate Box",
        price: 39.99,
        uid: "user678",
    },
    {
        category: 2,
        condition: 8,
        created_at: "2023-08-12",
        description: "Smart home assistant for modern households.",
        for_borrow: false,
        for_sale: true,
        index: 31,
        id: "product31",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Smart Home Assistant",
        price: 129.99,
        uid: "user345",
    },
    {
        category: 3,
        condition: 7,
        created_at: "2023-09-28",
        description: "Luxury fountain pen set for writing enthusiasts.",
        for_borrow: true,
        for_sale: true,
        index: 32,
        id: "product32",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Luxury Fountain Pen Set",
        price: 149.99,
        uid: "user234",
    },
    {
        category: 4,
        condition: 9,
        created_at: "2023-09-22",
        description: "DIY candle making kit for creative individuals.",
        for_borrow: true,
        for_sale: true,
        index: 33,
        id: "product33",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "DIY Candle Making Kit",
        price: 49.99,
        uid: "user567",
    },
    {
        category: 5,
        condition: 8,
        created_at: "2023-08-29",
        description: "Japanese tea ceremony set for tea enthusiasts.",
        for_borrow: true,
        for_sale: true,
        index: 34,
        id: "product34",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Japanese Tea Ceremony Set",
        price: 79.99,
        uid: "user890",
    },
    {
        category: 2,
        condition: 7,
        created_at: "2023-09-15",
        description: "Fitness tracker for health enthusiasts.",
        for_borrow: false,
        for_sale: true,
        index: 35,
        id: "product35",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Fitness Tracker",
        price: 89.99,
        uid: "user123",
    },
    {
        category: 3,
        condition: 9,
        created_at: "2023-08-18",
        description: "Vintage pocket watch for collectors.",
        for_borrow: true,
        for_sale: true,
        index: 36,
        id: "product36",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Vintage Pocket Watch",
        price: 199.99,
        uid: "user456",
    },
    {
        category: 4,
        condition: 8,
        created_at: "2023-09-25",
        description: "Embroidery starter kit for craft enthusiasts.",
        for_borrow: true,
        for_sale: true,
        index: 37,
        id: "product37",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Embroidery Starter Kit",
        price: 69.99,
        uid: "user678",
    },
    {
        category: 5,
        condition: 7,
        created_at: "2023-09-02",
        description: "Indian spice collection for culinary artists.",
        for_borrow: true,
        for_sale: true,
        index: 38,
        id: "product38",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Indian Spice Collection",
        price: 29.99,
        uid: "user789",
    },
    {
        category: 2,
        condition: 9,
        created_at: "2023-09-10",
        description: "Wireless over-ear headphones for music lovers.",
        for_borrow: false,
        for_sale: true,
        index: 39,
        id: "product39",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Wireless Over-Ear Headphones",
        price: 149.99,
        uid: "user234",
    },
    {
        category: 3,
        condition: 8,
        created_at: "2023-08-27",
        description: "Antique compass for collectors.",
        for_borrow: true,
        for_sale: true,
        index: 40,
        id: "product40",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Antique Compass",
        price: 99.99,
        uid: "user567",
    },
    {
        category: 1,
        condition: 9,
        created_at: "2023-09-18",
        description:
            "Organic food recipe book for health-conscious individuals.",
        for_borrow: true,
        for_sale: true,
        index: 41,
        id: "product41",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Organic Food Recipe Book",
        price: 39.99,
        uid: "user890",
    },
    {
        category: 5,
        condition: 7,
        created_at: "2023-09-15",
        description: "Chinese tea set for tea enthusiasts.",
        for_borrow: true,
        for_sale: true,
        index: 42,
        id: "product42",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Chinese Tea Set",
        price: 49.99,
        uid: "user123",
    },
    {
        category: 2,
        condition: 8,
        created_at: "2023-09-25",
        description: "Bluetooth portable printer for on-the-go printing.",
        for_borrow: false,
        for_sale: true,
        index: 43,
        id: "product43",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Bluetooth Portable Printer",
        price: 199.99,
        uid: "user456",
    },
    {
        category: 3,
        condition: 9,
        created_at: "2023-09-02",
        description: "Handcrafted quill pen for writing enthusiasts.",
        for_borrow: true,
        for_sale: true,
        index: 44,
        id: "product44",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Handcrafted Quill Pen",
        price: 89.99,
        uid: "user678",
    },
    {
        category: 4,
        condition: 7,
        created_at: "2023-09-10",
        description: "Cross-stitch embroidery set for craft enthusiasts.",
        for_borrow: true,
        for_sale: true,
        index: 45,
        id: "product45",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Cross-Stitch Embroidery Set",
        price: 69.99,
        uid: "user234",
    },
    {
        category: 5,
        condition: 8,
        created_at: "2023-08-18",
        description: "African tea collection for tea enthusiasts.",
        for_borrow: true,
        for_sale: true,
        index: 46,
        id: "product46",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "African Tea Collection",
        price: 29.99,
        uid: "user567",
    },
    {
        category: 2,
        condition: 9,
        created_at: "2023-09-28",
        description: "Wireless gaming mouse for gaming enthusiasts.",
        for_borrow: false,
        for_sale: true,
        index: 47,
        id: "product47",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Wireless Gaming Mouse",
        price: 49.99,
        uid: "user789",
    },
    {
        category: 3,
        condition: 7,
        created_at: "2023-09-22",
        description: "Ancient artifact replica for history enthusiasts.",
        for_borrow: true,
        for_sale: true,
        index: 48,
        id: "product48",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Ancient Artifact Replica",
        price: 99.99,
        uid: "user345",
    },

    {
        category: 1,
        condition: 8,
        created_at: "2023-10-10",
        description: "Herb garden starter kit for cooking enthusiasts.",
        for_borrow: true,
        for_sale: true,
        index: 49,
        id: "product49",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Herb Garden Starter Kit",
        price: 69.99,
        uid: "user234",
    },
    {
        category: 3,
        condition: 7,
        created_at: "2023-09-25",
        description: "Retro-style sunglasses for fashion-forward individuals.",
        for_borrow: false,
        for_sale: true,
        index: 50,
        id: "product50",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Retro-Style Sunglasses",
        price: 44.99,
        uid: "user789",
    },
    {
        category: 4,
        condition: 9,
        created_at: "2023-09-20",
        description: "DIY candle making kit for crafting enthusiasts.",
        for_borrow: true,
        for_sale: true,
        index: 51,
        id: "product51",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "DIY Candle Making Kit",
        price: 49.99,
        uid: "user345",
    },
    {
        category: 5,
        condition: 8,
        created_at: "2023-09-15",
        description: "Assorted organic honey collection for food enthusiasts.",
        for_borrow: true,
        for_sale: true,
        index: 52,
        id: "product52",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Organic Honey Collection",
        price: 29.99,
        uid: "user123",
    },
    {
        category: 2,
        condition: 7,
        created_at: "2023-09-10",
        description: "Compact portable projector for movie enthusiasts.",
        for_borrow: false,
        for_sale: true,
        index: 53,
        id: "product53",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Compact Portable Projector",
        price: 149.99,
        uid: "user567",
    },
    {
        category: 3,
        condition: 9,
        created_at: "2023-09-05",
        description: "Vintage-style leather handbag for fashion enthusiasts.",
        for_borrow: true,
        for_sale: true,
        index: 54,
        id: "product54",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Vintage-Style Leather Handbag",
        price: 79.99,
        uid: "user890",
    },
    {
        category: 1,
        condition: 8,
        created_at: "2023-08-31",
        description: "Essential kitchen tools set for cooking enthusiasts.",
        for_borrow: true,
        for_sale: true,
        index: 55,
        id: "product55",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Kitchen Tools Set",
        price: 39.99,
        uid: "user234",
    },
    {
        category: 5,
        condition: 7,
        created_at: "2023-08-27",
        description: "Collection of exotic spices for culinary explorers.",
        for_borrow: true,
        for_sale: true,
        index: 56,
        id: "product56",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Exotic Spices Collection",
        price: 49.99,
        uid: "user789",
    },
    {
        category: 2,
        condition: 9,
        created_at: "2023-08-23",
        description: "High-definition webcam for video conferencing.",
        for_borrow: false,
        for_sale: true,
        index: 57,
        id: "product57",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "HD Webcam",
        price: 69.99,
        uid: "user345",
    },
    {
        category: 4,
        condition: 8,
        created_at: "2023-08-19",
        description: "Stained glass art kit for creative enthusiasts.",
        for_borrow: true,
        for_sale: true,
        index: 58,
        id: "product58",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Stained Glass Art Kit",
        price: 59.99,
        uid: "user123",
    },
    {
        category: 1,
        condition: 7,
        created_at: "2023-08-15",
        description: "Home pizza making kit for pizza enthusiasts.",
        for_borrow: true,
        for_sale: true,
        index: 59,
        id: "product59",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Home Pizza Making Kit",
        price: 29.99,
        uid: "user567",
    },
    {
        category: 5,
        condition: 9,
        created_at: "2023-08-11",
        description: "Deluxe tea infuser set for tea enthusiasts.",
        for_borrow: true,
        for_sale: true,
        index: 60,
        id: "product60",
        image: [
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
            "https://images.placeholders.dev/?width=100&height=100",
        ],
        is_borrowed: false,
        is_borrowed_period: 0,
        is_sold: false,
        name: "Deluxe Tea Infuser Set",
        price: 19.99,
        uid: "user890",
    },
];

export default productsData;

export const addProducts = async () => {
    const productsDataCollection = collection(db, "products");
    productsData.forEach(async (product) => {
        addDoc(productsDataCollection, product);
    });
};
